config/routes.rb
Rails.application.routes.draw do
  root to: 'tickets#index'
  resources :tickets, only: %i[index show] do
    resources :comments, only: %i[create new]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def zendesk_client
    $ZENDESK_CLIENT
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    upload_to_zendesk(params[:body], params[:attachments])
    redirect_to ticket_path(params[:ticket_id])
  end

  def new; end

  private

  def upload_to_zendesk(comment_body, files)
    ticket.comment = { value: comment_body }
    files.each do |file|
      ticket.comment.uploads << file
    end
    ticket.save
  end

  def ticket
    @ticket ||= zendesk_client.tickets.find!(id: params[:ticket_id])
  end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  def index
    @tickets = zendesk_client.tickets
  end

  def show
    @ticket = zendesk_client.tickets.find!(id: params[:id], include: :comments)
  end

  def create
    redirect_to ticket_path(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/comments/new.js.erb
$("#attachments").append("<%= j(render('tickets/new_attachment')) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZendeskIntegration</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="row">
    <%= yield %>
  </body>
</html>

app/views/tickets/_new_attachment.html.erb
<div class="form-group row">
  <label for="attachment" class="col-sm-2 col-form-label">Attachment</label>
  <div class="col-sm-10">
    <input type="file" class="form-control-file" id="attachment" name="attachments[]">
  </div>
</div>

app/views/tickets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Tickets</h1>
    </div>
    <div class="col-12">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Subject</th>
            <th scope="col">Priority</th>
            <th scope="col">Status</th>
            <th scope="col">Created at</th>
            <th scope="col">Updated at</th>
          </tr>
        </thead>
        <tbody>
          <% @tickets.each do |ticket| %>
            <tr>
              <th scope="row"><%= ticket.id %></th>
              <td><%= link_to ticket.subject, ticket_path(ticket.id) %></td>
              <td><%= ticket.priority %></td>
              <td><%= ticket.status %></td>
              <td><%= ticket.created_at %></td>
              <td><%= ticket.updated_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tickets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Ticket #<%= @ticket.id %></h1>
      <h2><%= link_to 'Back to Tickets', tickets_path %></h2>
      <div class="form-group row">
        <label for="subject" class="col-sm-2 col-form-label">Subject</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control" id="subject" value="<%= @ticket.subject %>">
        </div>
      </div>
      <div class="form-group row">
        <label for="priority" class="col-sm-2 col-form-label">Priority</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control" id="priority" value="<%= @ticket.priority %>">
        </div>
      </div>
      <div class="form-group row">
        <label for="status" class="col-sm-2 col-form-label">Status</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control" id="status" value="<%= @ticket.status %>">
        </div>
      </div>
      <div class="form-group row">
        <label for="created_at" class="col-sm-2 col-form-label">Created at</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control" id="created_at" value="<%= @ticket.created_at %>">
        </div>
      </div>
      <div class="form-group row">
        <label for="updated_at" class="col-sm-2 col-form-label">Updated at</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control" id="updated_at" value="<%= @ticket.updated_at %>">
        </div>
      </div>
    </div>
    <div class="col-12">
      <h2>Comments</h2>
      <br>
      <% @ticket.comments.each do |comment| %>
        <div class="media">
          <% if comment&.author&.photo&.content_url %>
            <img width="40px" height="40px" src="<%= comment&.author&.photo&.content_url %>" class="mr-3" alt="<%= comment&.author&.photo&.content_url %>">
          <% else %>
            <img width="40px" height="40px" src="<%= asset_path('anonymous.png') %>" class="mr-3" alt="<%= asset_path('anonymous.png') %>">
          <% end %>
          <div class="media-body">
            <h5 class="mt-0"><%= comment.author.name %></h5>
            <%= comment.html_body.html_safe %>
            <ul class="list-unstyled">
              <% comment.attachments.each do |attachment| %>
                <li class="media">
                  <% if attachment.width.present? %>
                    <img height="64px" width="64px" src="<%= attachment.content_url %>" alt="<%= attachment.file_name %>" class="mr-3 rounded-sm">
                  <% else %>
                    <img height="64px" width="64px" src="<%= asset_path('file') %>" alt="<%= attachment.file_name %>" class="mr-3 rounded-sm">
                  <% end %>
                  <%= link_to attachment.file_name, attachment.content_url %>
                </li>
              <% end %>
            </ul>
            <div class="small">
              <%= comment.created_at %>
            </div>
          </div>
        </div>
        <hr>
      <% end %>
      <form action="<%= ticket_comments_path(@ticket.id) %>" method="post" enctype="multipart/form-data">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="form-group row">
          <label for="body" class="col-sm-2 col-form-label">Comment</label>
          <div class="col-sm-10">
            <textarea placeholder="Place your comment here" class="form-control" id="body" rows="5" name="body"></textarea>
          </div>
        </div>
        <div id="attachments">
          <%= render 'new_attachment' %>
        </div>
        <%= link_to 'Add new attachment', new_ticket_comment_path(@ticket.id, format: :js), remote: true, class: 'btn btn-secondary mb-2' %>
        <button type="submit" class="btn btn-primary mb-2">Comment</button>
      </form>
    </div>
  </div>
</div>